---
- name: Install Nginx and Update the OS
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Install Nginx
      apt: name=nginx update_cache=yes
    - name: Create /var/www/html directory
      file: path=/var/www/html state=directory owner=www-data group=www-data mode=0775
    - name: Copy index.html to /var/www/html
      copy: src=files/index.html dest=/var/www/html/index.html mode=0644
    - name: Copy nginx.conf configuration file to /etc/nginx
      copy: src=files/nginx.conf dest=/etc/nginx mode=0644
      notify:
         - restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
