# Install Docker
# Author: Patrick H. Mullins (pmullins11@mac.com)
# Created: 2016-12-03 - Modifed: 2016-12-12
# Required: Ansible 2.0

---
- name: Install Docker
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:

  - name: Make sure apt-transport-https is installed
    apt:
      name: apt-transport-https
      state: installed

  - name: Make sure ca-certificates is installed
    apt:
      name: ca-certificates
      state: installed

  - name: Add Docker repository key
    apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      state: present

  - name: Add Docker repository and update apt cache
    apt_repository:
      repo: "deb https://apt.dockerproject.org/repo debian-jessie main"
      update_cache: yes
      state: present

  - name: Install Docker
    apt:
      name: docker-engine
      state: installed

  - name: Enable Docker
    shell: systemctl enable docker
